'use strict';

var React = require('react');
var ReactDOM = require('react-dom');
var PouchDB = require('pouchdb');
var db = new PouchDB('dbname');

var CommentBox = React.createClass({
    getInitialState: function() {
        return {data: []};
    },
    loadCommentsFromServer: function() {
        db.allDocs({include_docs: true, descending: true}, function(err, doc) {
            this.setState({data: doc.rows});
            console.log('Successfully loaded comments');
        }.bind(this));
    },
    handleCommentSubmit: function(comment) {
        var comments = this.state.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment._id = Date.now().toString();
        var newComments = comments.concat([comment]);
        this.setState({data: newComments});
        db.put(comment, function callback(err, result) {
            if (err) {
                console.log('Error: ' + err);
            } else {
                console.log('Successfully posted a comment!');
            }
        });
    },
    componentDidMount: function() {
        this.loadCommentsFromServer();
        setInterval(this.loadCommentsFromServer, this.props.pollInterval);
    },
    render: function() {
        return (
        /*jshint ignore:start */
        <div className="commentBox">
            <h1>Comments</h1>
            <CommentList data={this.state.data} />
            <CommentForm onCommentSubmit={this.handleCommentSubmit} />
        </div>
        /*jshint ignore:end */
        );
    }
    });
    
    var CommentList = React.createClass({
    render: function() {
        var commentNodes = this.props.data.map(function(comment) {
        return (
            /*jshint ignore:start */
            <Comment author={comment.author} key={comment.id}>
            {comment.text}
            </Comment>
            /*jshint ignore:end */
        );
        });
        return (
        /*jshint ignore:start */
        <div className="commentList">
            {commentNodes}
        </div>
        /*jshint ignore:end */
        );
    }
    });
    
    var Comment = React.createClass({
    render: function() {
        return (
        /*jshint ignore:start */
        <div className="comment">
            <h2 className="commentAuthor">
            {this.props.author}
            </h2>
            {this.props.children}
        </div>
        /*jshint ignore:end */
        );
    }
    });
    
    var CommentForm = React.createClass({
    handleSubmit: function(e) {
        e.preventDefault();
        var author = this.refs.author.value.trim();
        var text = this.refs.text.value.trim();
        if (!text || !author) {
        return;
        }
        this.props.onCommentSubmit({author: author, text: text});
        this.refs.text.value = '';
        return;
    },
    render: function() {
        return (
        /*jshint ignore:start */
        <form className="commentForm" onSubmit={this.handleSubmit}>
            <input type="text" placeholder="Your name" ref="author" />
            <input type="text" placeholder="Say something..." ref="text" />
            <input type="submit" value="Post" />
        </form>
        /*jshint ignore:end */
        );
    }
    });
    
    ReactDOM.render(
    /*jshint ignore:start */
    <CommentBox url="/api/comments" pollInterval={2000} />,
    /*jshint ignore:end */
    document.getElementById('content')
    );